// taoke-uniapp/pages/binding/my-experts.vue
<!-- 我的专家 — 机构/经纪公司/经纪人/助理视角 -->
<template>
  <view class="page">
    <TkNavBar title="我的专家" left-icon="back" />

    <scroll-view scroll-y class="page__scroll" :style="{ paddingTop: navBarH + 'px' }">
      <view class="page__inner">
        <view class="head">
          <text class="head__count">共 {{ items.length }} 位</text>
          <view class="head__btn" @tap="showAdd = true">
            <text class="head__btn-txt">添加专家</text>
          </view>
        </view>

        <scroll-view scroll-x class="tabs">
          <view
            v-for="t in statusTabs"
            :key="t.label"
            class="tab"
            :class="{ 'tab--active': tab === t.value }"
            @tap="tab = t.value"
          >
            <text class="tab__txt">{{ t.label }}</text>
            <text v-if="t.value !== undefined" class="tab__cnt">({{ countByStatus(t.value) }})</text>
          </view>
        </scroll-view>

        <TkLoading v-if="loading" />
        <TkEmpty v-else-if="!filtered.length" icon="expert" text="暂无专家绑定" />
        <view v-else class="list">
          <view v-for="item in filtered" :key="itemKey(item)" class="card">
            <view class="card__head">
              <text class="card__name">{{ displayName(item) }}</text>
              <text class="card__badge">{{ item.statusLabel || statusLabel(item.status) }}</text>
            </view>
            <text class="card__meta">真实姓名：{{ item.counterpartRealName || '—' }}</text>
            <text class="card__meta">电话：{{ item.counterpartPhone || '—' }}</text>
            <text class="card__meta">
              {{ item.ifInitiator ? '我方发起邀请' : '对方发起申请' }}
              <text v-if="item.createdAt"> · {{ fmtDate(item.createdAt) }}</text>
            </text>
            <text v-if="item.note" class="card__note">备注：{{ item.note }}</text>
            <text v-if="item.rejectReason" class="card__reject">拒绝理由：{{ item.rejectReason }}</text>
            <view
              v-if="item.status === BINDING_STATUS.ACTIVE || (item.status === BINDING_STATUS.PENDING && item.ifInitiator)"
              class="card__actions"
            >
              <view class="card__act card__act--danger" @tap="handleUnbind(item)">
                <text>{{ item.status === BINDING_STATUS.PENDING ? '撤回邀请' : '解除绑定' }}</text>
              </view>
            </view>
          </view>
        </view>
      </view>
    </scroll-view>

    <view v-if="showAdd" class="modal" @tap.self="closeAdd">
      <view class="modal__panel" @tap.stop>
        <view class="modal__head">
          <text class="modal__title">添加专家</text>
          <view @tap="closeAdd"><TkIcon name="close" :size="32" color="#999" /></view>
        </view>
        <view class="modal__body">
          <text class="field__label">专家手机号</text>
          <view class="search-row">
            <input class="field__input" :value="phone" placeholder="请输入对方注册手机号" @input="phone = $event.detail.value" />
            <view class="search-row__btn" @tap="handleLookup">
              <text>{{ searching ? '查找中…' : '查找' }}</text>
            </view>
          </view>
          <text v-if="lookupError" class="hint hint--warn">{{ lookupError }}</text>
          <view v-if="picked" class="picked">
            <text class="picked__name">{{ picked.nickname || `用户#${picked.id}` }}</text>
            <text class="picked__phone">{{ picked.phone }}</text>
          </view>
          <text class="field__label">备注（可选）</text>
          <textarea class="field__textarea" :value="note" placeholder="向专家说明绑定意图" @input="note = $event.detail.value" />
        </view>
        <view class="modal__foot">
          <view class="modal__ghost" @tap="closeAdd"><text>取消</text></view>
          <view class="modal__primary" @tap="handleAdd">
            <text>{{ submitting ? '提交中…' : '发起绑定' }}</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, computed } from 'vue';
import { onShow } from '@dcloudio/uni-app';
import {
  listMyExpertsByRole,
  mapRoleToExpertBindingType,
  initiateBinding,
  unbind,
  lookupUserByPhone,
  BINDING_STATUS,
  BINDING_STATUS_LABEL,
} from '@/api/binding';
import { getNavBarHeight } from '@/utils/system';
import { requireLogin } from '@/utils/auth';
import { useUserStore } from '@/stores/user';

const navBarH = getNavBarHeight();
const userStore = useUserStore();

const loading = ref(true);
const items = ref([]);
const tab = ref(undefined);
const showAdd = ref(false);
const phone = ref('');
const note = ref('');
const picked = ref(null);
const searching = ref(false);
const submitting = ref(false);
const lookupError = ref('');

const statusTabs = [
  { label: '全部', value: undefined },
  { label: '已生效', value: BINDING_STATUS.ACTIVE },
  { label: '待确认', value: BINDING_STATUS.PENDING },
  { label: '已拒绝', value: BINDING_STATUS.REJECTED },
  { label: '已解绑', value: BINDING_STATUS.UNBOUND },
];

const filtered = computed(() => {
  if (tab.value === undefined) return items.value;
  return items.value.filter((b) => b.status === tab.value);
});

onShow(() => {
  if (!requireLogin()) return;
  fetchData();
});

async function fetchData() {
  loading.value = true;
  try {
    items.value = await listMyExpertsByRole(userStore.activeRole) || [];
  } catch (_) {
    items.value = [];
  } finally {
    loading.value = false;
  }
}

function countByStatus(status) {
  return items.value.filter((b) => b.status === status).length;
}

function itemKey(item) {
  return `${item.bindingType}-${item.id}`;
}

function displayName(item) {
  return item.counterpartNickname || item.counterpartRealName || `专家#${item.counterpartUserId}`;
}

function statusLabel(status) {
  return BINDING_STATUS_LABEL[status] || '—';
}

function fmtDate(v) {
  return v ? String(v).slice(0, 10) : '';
}

function closeAdd() {
  showAdd.value = false;
  phone.value = '';
  note.value = '';
  picked.value = null;
  lookupError.value = '';
}

async function handleLookup() {
  const p = phone.value.trim();
  if (!p) return uni.showToast({ title: '请输入手机号', icon: 'none' });
  searching.value = true;
  lookupError.value = '';
  picked.value = null;
  try {
    const found = await lookupUserByPhone(p);
    if (userStore.profile?.id != null && found.id === userStore.profile.id) {
      lookupError.value = '不能邀请自己作为专家';
      return;
    }
    if (!found.approvedTrainer) {
      lookupError.value = '该用户尚未通过专家审核，暂时无法添加';
      return;
    }
    picked.value = found;
  } catch (e) {
    if (e?.status === 404) {
      lookupError.value = '平台上没有该用户，请先引导对方注册并完成专家入驻';
    } else {
      lookupError.value = e?.message || '查找失败';
    }
  } finally {
    searching.value = false;
  }
}

async function handleAdd() {
  if (submitting.value || !picked.value) {
    return uni.showToast({ title: '请先查找用户', icon: 'none' });
  }
  const bindingType = mapRoleToExpertBindingType(userStore.activeRole);
  if (!bindingType) return uni.showToast({ title: '当前身份不支持添加专家', icon: 'none' });
  submitting.value = true;
  try {
    await initiateBinding({
      bindingType,
      targetUserId: picked.value.id,
      note: note.value.trim() || undefined,
    });
    uni.showToast({ title: '绑定请求已发送', icon: 'none' });
    closeAdd();
    await fetchData();
  } finally {
    submitting.value = false;
  }
}

function handleUnbind(item) {
  const isWithdraw = item.status === BINDING_STATUS.PENDING;
  uni.showModal({
    title: isWithdraw ? '撤回邀请' : '解除绑定',
    content: isWithdraw ? '确定撤回该绑定邀请？' : '确定解除与该专家的绑定？',
    confirmColor: '#DC2626',
    success: async (res) => {
      if (!res.confirm) return;
      await unbind(item.bindingType, item.id);
      uni.showToast({ title: isWithdraw ? '已撤回' : '已解除绑定', icon: 'none' });
      await fetchData();
    },
  });
}
</script>

<style lang="scss" scoped>
.page { min-height: 100vh; background: $tk-bg-page; }
.page__scroll { height: 100vh; }
.page__inner { padding: $tk-sp-3; display: flex; flex-direction: column; gap: $tk-sp-3; padding-bottom: 40rpx; }

.head {
  display: flex; align-items: center; justify-content: space-between;
  &__count { font-size: $tk-fs-sm; color: $tk-text-3; }
  &__btn { padding: 12rpx 28rpx; background: $tk-primary; border-radius: $tk-radius-md; }
  &__btn-txt { color: #fff; font-size: $tk-fs-sm; font-weight: 600; }
}

.tabs { white-space: nowrap; }
.tab {
  display: inline-flex; align-items: center; gap: 4rpx;
  padding: 12rpx 24rpx; margin-right: 12rpx;
  background: $tk-bg-card; border-radius: $tk-radius-full;
  &__txt { font-size: $tk-fs-sm; color: $tk-text-2; }
  &__cnt { font-size: $tk-fs-xs; color: $tk-text-4; }
  &--active { background: $tk-primary; .tab__txt, .tab__cnt { color: #fff; } }
}

.list { display: flex; flex-direction: column; gap: $tk-sp-2; }
.card {
  background: $tk-bg-card; border-radius: $tk-radius-lg; padding: $tk-sp-3;
  box-shadow: $tk-shadow-card; display: flex; flex-direction: column; gap: 8rpx;
  &__head { display: flex; align-items: center; justify-content: space-between; gap: $tk-sp-2; }
  &__name { flex: 1; font-size: $tk-fs-md; font-weight: 700; color: $tk-text-1; }
  &__badge { font-size: $tk-fs-xs; color: $tk-primary; background: $tk-primary-soft; padding: 4rpx 12rpx; border-radius: $tk-radius-xs; }
  &__meta { font-size: $tk-fs-xs; color: $tk-text-3; }
  &__note { font-size: $tk-fs-xs; color: $tk-text-2; }
  &__reject { font-size: $tk-fs-xs; color: #DC2626; }
  &__actions { margin-top: 8rpx; display: flex; justify-content: flex-end; }
  &__act {
    padding: 10rpx 24rpx; border-radius: $tk-radius-md; font-size: $tk-fs-xs;
    &--danger { border: 2rpx solid rgba(220, 38, 38, 0.3); color: #DC2626; }
  }
}

.modal {
  position: fixed; inset: 0; z-index: 100; background: rgba(0, 0, 0, 0.45);
  display: flex; align-items: center; justify-content: center; padding: $tk-sp-4;
  &__panel { width: 100%; max-width: 640rpx; background: #fff; border-radius: $tk-radius-lg; overflow: hidden; }
  &__head { padding: $tk-sp-3 $tk-sp-4; border-bottom: 2rpx solid $tk-divider-light; display: flex; align-items: center; justify-content: space-between; }
  &__title { font-size: $tk-fs-lg; font-weight: 700; color: $tk-text-1; }
  &__body { padding: $tk-sp-4; display: flex; flex-direction: column; gap: $tk-sp-2; }
  &__foot { padding: $tk-sp-3 $tk-sp-4; border-top: 2rpx solid $tk-divider-light; display: flex; gap: $tk-sp-2; justify-content: flex-end; }
  &__ghost, &__primary { padding: 16rpx 32rpx; border-radius: $tk-radius-md; font-size: $tk-fs-sm; }
  &__ghost { border: 2rpx solid $tk-divider-light; color: $tk-text-2; }
  &__primary { background: $tk-primary; color: #fff; font-weight: 600; }
}

.field__label { display: block; font-size: $tk-fs-sm; color: $tk-text-3; margin-bottom: 8rpx; }
.field__input, .field__textarea {
  width: 100%; padding: 20rpx 24rpx; background: $tk-bg-page; border-radius: $tk-radius-md;
  font-size: $tk-fs-md; color: $tk-text-1; box-sizing: border-box;
}
.field__textarea { min-height: 160rpx; }
.search-row { display: flex; gap: $tk-sp-2; align-items: center; &__btn { flex-shrink: 0; padding: 20rpx 24rpx; background: $tk-primary; border-radius: $tk-radius-md; color: #fff; font-size: $tk-fs-sm; } }
.hint { font-size: $tk-fs-xs; &--warn { color: #D97706; } }
.picked { padding: $tk-sp-2 $tk-sp-3; background: $tk-primary-soft; border-radius: $tk-radius-md; &__name { display: block; font-size: $tk-fs-md; font-weight: 600; color: $tk-text-1; } &__phone { font-size: $tk-fs-xs; color: $tk-text-3; } }
</style>

// frontend/src/app/[locale]/(usercenter)/dashboard/my-experts/page.tsx
'use client';

import { useEffect, useState, useCallback } from 'react';
import Image from 'next/image';
import { toast } from 'sonner';
import {
  Users, Plus, Search, X, Loader2, AlertCircle,
} from 'lucide-react';
import { useAuth } from '@/lib/auth/auth-context';
import {
  listInstitutionTrainers,
  listEnterpriseAgentTrainers,
  listAgentTrainers,
  listAssistantTrainers,
  listManagedTrainers,
  initiateBinding,
  unbind,
  lookupUserByPhone,
  type LookupUserResult,
} from '@/features/binding/api/service';
import {
  BINDING_STATUS,
  type BindingItem,
  type BindingType,
} from '@/features/binding/api/types';
import { getDisplayStatusLabel } from '@/features/binding/lib/status-label';

const STATUS_TABS: { label: string; value: number | undefined }[] = [
  { label: '全部', value: undefined },
  { label: '已生效', value: BINDING_STATUS.ACTIVE },
  { label: '待确认', value: BINDING_STATUS.PENDING },
  { label: '已拒绝', value: BINDING_STATUS.REJECTED },
  { label: '已解绑', value: BINDING_STATUS.UNBOUND },
];

const STATUS_BADGE: Record<number, string> = {
  [BINDING_STATUS.ACTIVE]: 'bg-green-50 text-green-600 border-green-100',
  [BINDING_STATUS.PENDING]: 'bg-amber-50 text-amber-600 border-amber-100',
  [BINDING_STATUS.REJECTED]: 'bg-red-50 text-red-600 border-red-100',
  [BINDING_STATUS.UNBOUND]: 'bg-slate-100 text-slate-500 border-slate-200',
};

/**
 * 我的专家 — 培训机构 / 经纪公司 / 经纪人 / 专家助理 视角
 *
 * @author Fangxinxin
 * @date 2026-04-21 17:30
 */
export default function MyExpertsPage() {
  const { activeRole } = useAuth();
  const [items, setItems] = useState<BindingItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState<number | undefined>(undefined);
  const [adding, setAdding] = useState(false);

  const role = activeRole;
  const bindingType: BindingType = mapRoleToType(role);
  const readOnly = role === 'INSTITUTION_EMPLOYEE';

  const fetchData = useCallback(async () => {
    setLoading(true);
    try {
      const fetcher = pickListFetcher(role);
      const list = fetcher ? await fetcher() : [];
      setItems(list);
    } finally {
      setLoading(false);
    }
  }, [role]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  const filtered = tab == null ? items : items.filter((b) => b.status === tab);

  const handleUnbind = async (item: BindingItem) => {
    if (!confirm('确定要解除与该专家的绑定吗？')) return;
    try {
      await unbind(item.bindingType, item.id);
      toast.success('已解除绑定');
      await fetchData();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : '操作失败');
    }
  };

  return (
    <section className="bg-white rounded-lg shadow-sm border border-slate-200 overflow-hidden min-h-[500px]">
      <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <h2 className="text-lg font-bold text-gray-800">我的专家</h2>
          <span className="text-xs text-gray-400">{items.length} 位</span>
        </div>
        {!readOnly && (
          <button
            type="button"
            onClick={() => setAdding(true)}
            className="inline-flex items-center gap-1.5 bg-primary text-white text-sm px-4 py-2 rounded-lg hover:bg-primary/90 transition-colors"
          >
            <Plus className="size-4" />
            添加专家
          </button>
        )}
        {readOnly && (
          <span className="text-xs text-gray-400">只读视图，权限来自所属机构</span>
        )}
      </div>

      {!readOnly && (
      <div className="px-6 pt-4 pb-2 flex gap-1 flex-wrap">
        {STATUS_TABS.map((t) => (
          <button
            key={t.label}
            type="button"
            onClick={() => setTab(t.value)}
            className={`px-3.5 py-1.5 text-sm rounded-full transition-colors ${
              tab === t.value
                ? 'bg-primary text-white'
                : 'bg-slate-100 text-gray-600 hover:bg-slate-200'
            }`}
          >
            {t.label}
            {t.value !== undefined && (
              <span className="ml-1 opacity-60">
                ({items.filter((b) => b.status === t.value).length})
              </span>
            )}
          </button>
        ))}
      </div>
      )}

      <div className="px-6 pb-6 pt-3">
        {loading ? (
          <div className="flex items-center justify-center py-20 text-gray-400">
            <Loader2 className="size-6 animate-spin" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-gray-400">
            <Users className="size-12 mb-3 text-gray-300" />
            <p className="text-sm">暂无数据</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filtered.map((item) => (
              <ExpertCard
                key={`${item.bindingType}-${item.id}`}
                item={item}
                readOnly={readOnly}
                onUnbind={handleUnbind}
              />
            ))}
          </div>
        )}
      </div>

      {adding && (
        <AddExpertDialog
          bindingType={bindingType}
          onClose={() => setAdding(false)}
          onAdded={() => {
            setAdding(false);
            fetchData();
          }}
        />
      )}
    </section>
  );
}

/* ============================================================ */

function mapRoleToType(role: string | undefined): BindingType {
  switch (role) {
    case 'INSTITUTION': return 'INSTITUTION_TRAINER';
    case 'ENTERPRISE_AGENT': return 'ENTERPRISE_AGENT_TRAINER';
    case 'AGENT': return 'AGENT_TRAINER';
    case 'ASSISTANT': return 'ASSISTANT_TRAINER';
    default: return 'INSTITUTION_TRAINER';
  }
}

function pickListFetcher(role: string | undefined): (() => Promise<BindingItem[]>) | null {
  switch (role) {
    case 'INSTITUTION': return listInstitutionTrainers;
    case 'ENTERPRISE_AGENT': return listEnterpriseAgentTrainers;
    case 'AGENT': return listAgentTrainers;
    case 'ASSISTANT': return listAssistantTrainers;
    case 'INSTITUTION_EMPLOYEE': return listManagedTrainers;
    default: return null;
  }
}

function ExpertCard({
  item,
  readOnly,
  onUnbind,
}: {
  item: BindingItem;
  readOnly?: boolean;
  onUnbind: (i: BindingItem) => void;
}) {
  const status = item.status;
  return (
    <div className="border border-slate-200 rounded-lg p-4 hover:border-primary/40 hover:shadow-md transition-all">
      <div className="flex gap-3">
        {item.counterpartAvatarUrl ? (
          <Image
            src={item.counterpartAvatarUrl}
            alt={item.counterpartNickname || ''}
            width={48}
            height={48}
            className="size-12 rounded-full object-cover bg-slate-100"
          />
        ) : (
          <div className="size-12 rounded-full bg-slate-100 text-slate-300 flex items-center justify-center">
            <Users className="size-6" />
          </div>
        )}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <span className="font-medium text-gray-800 truncate">
              {item.counterpartNickname || `专家#${item.counterpartUserId}`}
            </span>
            <span className={`text-[11px] px-2 py-0.5 rounded-full border shrink-0 ${STATUS_BADGE[status] || ''}`}>
              {getDisplayStatusLabel(item)}
            </span>
          </div>
          {/* 真实姓名 / 电话：无值时占位为空，便于一行式辨识 */}
          <div className="flex flex-wrap items-center gap-x-3 gap-y-0.5 text-xs text-gray-500 mt-1">
            <span>真实姓名：{item.counterpartRealName || ''}</span>
            <span>电话：{item.counterpartPhone || ''}</span>
          </div>
          <div className="text-xs text-gray-400 mt-1">
            {item.ifInitiator ? '我方发起邀请' : '对方发起申请'} · {item.createdAt?.slice(0, 10)}
          </div>
          {item.note && <div className="text-xs text-gray-500 mt-1 line-clamp-2">备注：{item.note}</div>}
          {item.rejectReason && (
            <div className="flex items-start gap-1 text-xs text-red-500 mt-1">
              <AlertCircle className="size-3 mt-0.5 shrink-0" />
              <span className="line-clamp-2">拒绝理由：{item.rejectReason}</span>
            </div>
          )}
        </div>
      </div>
      {!readOnly && (
        <div className="mt-3 flex flex-wrap gap-2 justify-end">
          {/* 仅在 ACTIVE 或自己发起的 PENDING 上显示撤回/解绑 — 与 my-agents-team 视角一致 */}
          {(status === BINDING_STATUS.ACTIVE
            || (status === BINDING_STATUS.PENDING && item.ifInitiator)) && (
            <button
              type="button"
              onClick={() => onUnbind(item)}
              className="inline-flex items-center gap-1 text-xs px-3 py-1.5 rounded border border-red-200 text-red-500 hover:bg-red-50 transition-colors"
            >
              <X className="size-3.5" />
              {status === BINDING_STATUS.PENDING ? '撤回邀请' : '解除绑定'}
            </button>
          )}
        </div>
      )}
    </div>
  );
}

/* ============================================================ */

function AddExpertDialog({
  bindingType,
  onClose,
  onAdded,
}: {
  bindingType: BindingType;
  onClose: () => void;
  onAdded: () => void;
}) {
  const { user } = useAuth();
  const [phone, setPhone] = useState('');
  const [searching, setSearching] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [picked, setPicked] = useState<LookupUserResult | null>(null);
  const [note, setNote] = useState('');

  const handleSearch = async () => {
    if (!phone.trim()) {
      toast.error('请先输入手机号');
      return;
    }
    setSearching(true);
    try {
      const found = await lookupUserByPhone(phone.trim());
      // 即时拦截自邀请，避免点提交后才被后端兜底拒绝
      if (user?.id != null && found.id === user.id) {
        setPicked(null);
        toast.error('不能邀请自己作为专家');
        return;
      }
      setPicked(found);
    } catch (err) {
      setPicked(null);
      toast.error(err instanceof Error ? err.message : '未找到该手机号对应用户，请确认对方已注册');
    } finally {
      setSearching(false);
    }
  };

  const handleSubmit = async () => {
    if (!picked) {
      toast.error('请先按手机号查找用户');
      return;
    }
    setSubmitting(true);
    try {
      await initiateBinding({
        bindingType,
        targetUserId: picked.id,
        note: note.trim() || undefined,
      });
      toast.success('绑定请求已发送，等待专家确认');
      onAdded();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : '发起失败');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-lg">
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between">
          <h3 className="font-bold text-gray-800">添加专家</h3>
          <button
            type="button"
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors"
          >
            <X className="size-5" />
          </button>
        </div>
        <div className="p-6 space-y-4">
          <div>
            <label className="block text-sm text-gray-700 mb-1">专家手机号</label>
            <div className="flex gap-2">
              <input
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                placeholder="请输入对方注册的手机号"
                className="flex-1 border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary"
              />
              <button
                type="button"
                onClick={handleSearch}
                disabled={searching}
                className="inline-flex items-center gap-1 bg-primary text-white text-sm px-4 py-2 rounded-lg hover:bg-primary/90 disabled:opacity-50"
              >
                {searching ? <Loader2 className="size-4 animate-spin" /> : <Search className="size-4" />}
                查找
              </button>
            </div>
          </div>

          {picked && (
            <div className="border border-primary/30 bg-primary/5 rounded-lg p-3 flex items-center gap-3">
              {picked.avatarUrl ? (
                <Image
                  src={picked.avatarUrl}
                  alt={picked.nickname || ''}
                  width={40}
                  height={40}
                  className="size-10 rounded-full object-cover bg-slate-100"
                />
              ) : (
                <div className="size-10 rounded-full bg-slate-100 text-slate-300 flex items-center justify-center">
                  <Users className="size-5" />
                </div>
              )}
              <div className="flex-1 min-w-0">
                <div className="text-sm font-medium text-gray-800 truncate">
                  {picked.nickname || `用户#${picked.id}`}
                </div>
                <div className="text-xs text-gray-500">{picked.phone}</div>
              </div>
            </div>
          )}

          <div>
            <label className="block text-sm text-gray-700 mb-1">备注（可选）</label>
            <textarea
              value={note}
              onChange={(e) => setNote(e.target.value)}
              rows={3}
              placeholder="向专家说明绑定意图（可选）"
              className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary"
            />
          </div>
        </div>
        <div className="px-6 py-4 border-t border-slate-200 flex justify-end gap-2">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-sm text-gray-600 border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors"
          >
            取消
          </button>
          <button
            type="button"
            disabled={submitting || !picked}
            onClick={handleSubmit}
            className="inline-flex items-center gap-1 bg-primary text-white text-sm px-4 py-2 rounded-lg hover:bg-primary/90 disabled:opacity-50"
          >
            {submitting && <Loader2 className="size-4 animate-spin" />}
            发起绑定
          </button>
        </div>
      </div>
    </div>
  );
}
