// frontend/src/app/[locale]/(usercenter)/dashboard/orders/invoice/page.tsx
'use client';

import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { ArrowLeft, CheckCircle, Info, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { Link, useRouter } from '@/i18n/navigation';
import { ROUTES } from '@/config/routes';
import { storage } from '@/lib/storage';
import { TOKEN_KEY } from '@/lib/auth/constants';
import { getMyProfile } from '@/features/user/api/service';
import {
  getOrderDetail,
  getInvoiceRequest,
  submitInvoiceRequest,
} from '@/features/order/api/service';
import type {
  OrderVO,
  InvoiceRequestVO,
  InvoiceType,
  InvoiceTitleType,
} from '@/features/order/api/types';

const INVOICE_TYPE_LABELS: Record<InvoiceType, string> = {
  SPECIAL: '全电发票-增值税专用发票',
  NORMAL: '全电发票-普通发票',
};

const INVOICE_STATUS_LABELS: Record<number, string> = {
  0: '待开票',
  1: '已开票',
  2: '已驳回',
};

function FieldRow({
  label,
  required,
  children,
}: {
  label: string;
  required?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div className="flex items-start gap-4">
      <label className="w-36 shrink-0 text-right text-sm text-gray-600 pt-2">
        {required && <span className="text-primary mr-0.5">*</span>}
        {label}：
      </label>
      <div className="flex-1 max-w-md">{children}</div>
    </div>
  );
}

const INPUT_CLS =
  'w-full border border-slate-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:border-primary focus:ring-1 focus:ring-primary';

function InvoicePageInner() {
  const searchParams = useSearchParams();
  const router = useRouter();
  const orderNo = searchParams.get('orderNo') || '';

  const [loading, setLoading] = useState(true);
  const [order, setOrder] = useState<OrderVO | null>(null);
  const [existing, setExisting] = useState<InvoiceRequestVO | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // 表单字段
  const [invoiceType, setInvoiceType] = useState<InvoiceType>('NORMAL');
  const [titleType, setTitleType] = useState<InvoiceTitleType>('PERSONAL');
  const [title, setTitle] = useState('');
  const [taxNo, setTaxNo] = useState('');
  const [bankName, setBankName] = useState('');
  const [bankAccount, setBankAccount] = useState('');
  const [companyAddress, setCompanyAddress] = useState('');
  const [companyPhone, setCompanyPhone] = useState('');
  const [email, setEmail] = useState('');

  useEffect(() => {
    if (!orderNo) {
      setLoading(false);
      return;
    }
    let cancelled = false;

    const load = async () => {
      try {
        const tokenData = storage.get<{ accessToken?: string }>(TOKEN_KEY);
        const [orderRes, invoiceRes, profileRes] = await Promise.all([
          getOrderDetail(orderNo),
          getInvoiceRequest(orderNo),
          tokenData?.accessToken
            ? getMyProfile(tokenData.accessToken).catch(() => null)
            : Promise.resolve(null),
        ]);
        if (cancelled) return;
        setOrder(orderRes);
        setExisting(invoiceRes);
        // 默认填写用户在淘课网上留的邮箱，支持修改
        if (profileRes?.data?.email) {
          setEmail(profileRes.data.email);
        }
      } catch {
        // 错误已弹出
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    load();

    return () => {
      cancelled = true;
    };
  }, [orderNo]);

  const isCompany = titleType === 'COMPANY';

  const handleSubmit = async () => {
    if (!title.trim()) {
      toast.error('请填写发票抬头');
      return;
    }
    if (isCompany && !taxNo.trim()) {
      toast.error('企业抬头需填写纳税人识别号');
      return;
    }
    if (!email.trim()) {
      toast.error('请填写接收发票的邮箱');
      return;
    }
    setSubmitting(true);
    try {
      const result = await submitInvoiceRequest(orderNo, {
        invoiceType,
        titleType,
        title: title.trim(),
        taxNo: taxNo.trim(),
        bankName: bankName.trim(),
        bankAccount: bankAccount.trim(),
        companyAddress: companyAddress.trim(),
        companyPhone: companyPhone.trim(),
        email: email.trim(),
      });
      setExisting(result);
      toast.success('发票申请已提交');
    } catch {
      // 错误已弹出
    } finally {
      setSubmitting(false);
    }
  };

  if (!orderNo) {
    return (
      <section className="bg-white rounded-lg shadow-sm border border-slate-200 p-10 text-center text-gray-500">
        缺少订单号参数
      </section>
    );
  }

  if (loading) {
    return (
      <section className="bg-white rounded-lg shadow-sm border border-slate-200 p-10 flex items-center justify-center text-gray-400">
        <Loader2 className="size-5 animate-spin mr-2" />
        加载中...
      </section>
    );
  }

  return (
    <section className="bg-white rounded-lg shadow-sm border border-slate-200 overflow-hidden min-h-[500px]">
      <div className="px-6 py-4 border-b border-slate-200 flex items-center gap-3">
        <Link
          href={ROUTES.UC_ORDERS}
          className="text-gray-500 hover:text-primary flex items-center gap-1 text-sm"
        >
          <ArrowLeft className="size-4" />
          返回订单
        </Link>
        <h2 className="text-[15px] font-bold text-gray-800">申请发票</h2>
        <span className="text-xs text-gray-400">订单号：{orderNo}</span>
      </div>

      {/* 提示条 */}
      <div className="mx-6 mt-5 flex items-start gap-2 rounded-md bg-amber-50 border border-amber-200 px-4 py-3 text-xs text-amber-700 leading-5">
        <Info className="size-4 shrink-0 mt-0.5" />
        电子发票与纸质发票具有同等法律效力，可支持报销入账；同时根据增值税管理办法要求，如需为企业开具增值税发票，需提供纳税人识别号或统一社会信用代码，否则该发票无法作为税收凭证。
      </div>

      {existing ? (
        /* 已申请过 — 展示申请记录 */
        <div className="p-6">
          <div className="flex items-center gap-2 mb-5">
            <CheckCircle className="size-5 text-green-600" />
            <span className="font-medium text-gray-800">
              发票申请已提交（{INVOICE_STATUS_LABELS[existing.status] ?? '处理中'}）
            </span>
          </div>
          <div className="space-y-3 text-sm text-gray-600 max-w-lg">
            <div className="flex justify-between border-b border-slate-100 pb-2">
              <span className="text-gray-400">发票类型</span>
              <span>{INVOICE_TYPE_LABELS[existing.invoiceType]}</span>
            </div>
            <div className="flex justify-between border-b border-slate-100 pb-2">
              <span className="text-gray-400">抬头类型</span>
              <span>{existing.titleType === 'COMPANY' ? '企业' : '个人'}</span>
            </div>
            <div className="flex justify-between border-b border-slate-100 pb-2">
              <span className="text-gray-400">开票金额</span>
              <span className="text-primary font-bold">¥{existing.amount.toFixed(2)}</span>
            </div>
            <div className="flex justify-between border-b border-slate-100 pb-2">
              <span className="text-gray-400">发票抬头</span>
              <span>{existing.title}</span>
            </div>
            {existing.titleType === 'COMPANY' && (
              <>
                <div className="flex justify-between border-b border-slate-100 pb-2">
                  <span className="text-gray-400">纳税人识别号</span>
                  <span>{existing.taxNo}</span>
                </div>
                {existing.bankName && (
                  <div className="flex justify-between border-b border-slate-100 pb-2">
                    <span className="text-gray-400">开户银行</span>
                    <span>{existing.bankName}</span>
                  </div>
                )}
                {existing.bankAccount && (
                  <div className="flex justify-between border-b border-slate-100 pb-2">
                    <span className="text-gray-400">银行账号</span>
                    <span>{existing.bankAccount}</span>
                  </div>
                )}
                {existing.companyAddress && (
                  <div className="flex justify-between border-b border-slate-100 pb-2">
                    <span className="text-gray-400">企业地址</span>
                    <span>{existing.companyAddress}</span>
                  </div>
                )}
                {existing.companyPhone && (
                  <div className="flex justify-between border-b border-slate-100 pb-2">
                    <span className="text-gray-400">企业电话</span>
                    <span>{existing.companyPhone}</span>
                  </div>
                )}
              </>
            )}
            <div className="flex justify-between border-b border-slate-100 pb-2">
              <span className="text-gray-400">接收发票的邮箱</span>
              <span>{existing.email}</span>
            </div>
          </div>
          <button
            type="button"
            onClick={() => router.push(ROUTES.UC_ORDERS)}
            className="mt-6 px-6 py-2 border border-slate-300 rounded text-sm text-gray-600 hover:border-primary hover:text-primary transition-colors"
          >
            返回我的订单
          </button>
        </div>
      ) : (
        /* 申请表单 */
        <div className="p-6 flex flex-col gap-5">
          <FieldRow label="发票类型" required>
            <div className="flex flex-wrap gap-5 pt-2">
              {(Object.keys(INVOICE_TYPE_LABELS) as InvoiceType[]).map((t) => (
                <label key={t} className="flex items-center gap-1.5 text-sm cursor-pointer">
                  <input
                    type="radio"
                    name="invoiceType"
                    checked={invoiceType === t}
                    onChange={() => setInvoiceType(t)}
                    className="accent-primary"
                  />
                  {INVOICE_TYPE_LABELS[t]}
                </label>
              ))}
            </div>
          </FieldRow>

          <FieldRow label="抬头类型" required>
            <div className="flex gap-5 pt-2">
              {(
                [
                  ['PERSONAL', '个人'],
                  ['COMPANY', '企业'],
                ] as [InvoiceTitleType, string][]
              ).map(([t, label]) => (
                <label key={t} className="flex items-center gap-1.5 text-sm cursor-pointer">
                  <input
                    type="radio"
                    name="titleType"
                    checked={titleType === t}
                    onChange={() => setTitleType(t)}
                    className="accent-primary"
                  />
                  {label}
                </label>
              ))}
            </div>
          </FieldRow>

          <FieldRow label="开票金额" required>
            <input
              type="text"
              value={order ? `¥${order.payAmount.toFixed(2)}` : ''}
              readOnly
              disabled
              className={`${INPUT_CLS} bg-slate-50 text-gray-500 cursor-not-allowed`}
            />
            <p className="text-xs text-gray-400 mt-1">默认为该订单实付金额，不可修改</p>
          </FieldRow>

          <FieldRow label="发票抬头" required>
            <input
              type="text"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder={isCompany ? '请填写企业名称' : '请填写个人姓名'}
              className={INPUT_CLS}
            />
          </FieldRow>

          {isCompany && (
            <>
              <FieldRow label="纳税人识别号" required>
                <input
                  type="text"
                  value={taxNo}
                  onChange={(e) => setTaxNo(e.target.value)}
                  placeholder="请填写纳税人识别号或统一社会信用代码"
                  className={INPUT_CLS}
                />
              </FieldRow>
              <FieldRow label="开户银行">
                <input
                  type="text"
                  value={bankName}
                  onChange={(e) => setBankName(e.target.value)}
                  placeholder="请填写开户银行"
                  className={INPUT_CLS}
                />
              </FieldRow>
              <FieldRow label="银行账号">
                <input
                  type="text"
                  value={bankAccount}
                  onChange={(e) => setBankAccount(e.target.value)}
                  placeholder="请填写银行账号"
                  className={INPUT_CLS}
                />
              </FieldRow>
              <FieldRow label="企业地址">
                <input
                  type="text"
                  value={companyAddress}
                  onChange={(e) => setCompanyAddress(e.target.value)}
                  placeholder="请填写企业地址"
                  className={INPUT_CLS}
                />
              </FieldRow>
              <FieldRow label="企业电话">
                <input
                  type="text"
                  value={companyPhone}
                  onChange={(e) => setCompanyPhone(e.target.value)}
                  placeholder="请填写企业电话"
                  className={INPUT_CLS}
                />
              </FieldRow>
            </>
          )}

          <FieldRow label="接收发票的邮箱" required>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="发票将发送至该邮箱"
              className={INPUT_CLS}
            />
            <p className="text-xs text-gray-400 mt-1">默认为您在淘课网预留的邮箱，可修改</p>
          </FieldRow>

          <div className="flex items-center gap-4 pl-40 mt-2">
            <button
              type="button"
              onClick={handleSubmit}
              disabled={submitting}
              className="px-8 py-2.5 bg-primary text-white font-medium rounded hover:bg-primary/90 transition-colors disabled:opacity-50 text-sm"
            >
              {submitting ? '提交中...' : '提交申请'}
            </button>
            <Link
              href={ROUTES.UC_ORDERS}
              className="px-8 py-2.5 border border-slate-300 rounded text-sm text-gray-600 hover:border-primary hover:text-primary transition-colors"
            >
              取消
            </Link>
          </div>
        </div>
      )}
    </section>
  );
}

/**
 * 申请发票页 — /dashboard/orders/invoice?orderNo=xxx
 *
 * @author Fangxinxin
 * @date 2026-06-11 14:00
 */
export default function InvoicePage() {
  return (
    <Suspense fallback={null}>
      <InvoicePageInner />
    </Suspense>
  );
}

// taoke-uniapp/pages/order/invoice.vue
<!-- 申请发票 — 对齐 PC dashboard/orders/invoice -->
<template>
  <view class="page">
    <TkNavBar title="申请发票" left-icon="back" />

    <scroll-view scroll-y class="page__scroll" :style="{ paddingTop: navBarH + 'px' }">
      <view class="page__inner">
        <TkLoading v-if="loading" />
        <TkEmpty v-else-if="!orderNo" text="缺少订单号" />

        <template v-else-if="existing">
          <view class="status-card">
            <text class="status-card__title">发票申请已提交</text>
            <text class="status-card__sub">{{ invoiceStatusLabel(existing.status) }}</text>
          </view>
          <view class="readonly">
            <view class="row"><text class="row__k">发票类型</text><text class="row__v">{{ invoiceTypeLabel(existing.invoiceType) }}</text></view>
            <view class="row"><text class="row__k">抬头类型</text><text class="row__v">{{ existing.titleType === 'COMPANY' ? '企业' : '个人' }}</text></view>
            <view class="row"><text class="row__k">开票金额</text><text class="row__v row__v--price">¥ {{ formatAmount(existing.amount) }}</text></view>
            <view class="row"><text class="row__k">发票抬头</text><text class="row__v">{{ existing.title }}</text></view>
            <view v-if="existing.titleType === 'COMPANY'" class="row">
              <text class="row__k">纳税人识别号</text><text class="row__v">{{ existing.taxNo }}</text>
            </view>
            <view class="row"><text class="row__k">接收邮箱</text><text class="row__v">{{ existing.email }}</text></view>
          </view>
        </template>

        <template v-else>
          <view class="tip">
            <text class="tip__txt">电子发票与纸质发票具有同等法律效力。企业抬头需填写纳税人识别号。</text>
          </view>

          <view class="form">
            <view class="field">
              <text class="field__label">发票类型</text>
              <radio-group class="radio-group" @change="onInvoiceTypeChange">
                <label v-for="opt in invoiceTypeOptions" :key="opt.value" class="radio-row">
                  <radio :value="opt.value" :checked="invoiceType === opt.value" color="#E62117" />
                  <text>{{ opt.label }}</text>
                </label>
              </radio-group>
            </view>

            <view class="field">
              <text class="field__label">抬头类型</text>
              <radio-group class="radio-group" @change="onTitleTypeChange">
                <label class="radio-row">
                  <radio value="PERSONAL" :checked="titleType === 'PERSONAL'" color="#E62117" />
                  <text>个人</text>
                </label>
                <label class="radio-row">
                  <radio value="COMPANY" :checked="titleType === 'COMPANY'" color="#E62117" />
                  <text>企业</text>
                </label>
              </radio-group>
            </view>

            <view class="field">
              <text class="field__label">发票抬头 <text class="req">*</text></text>
              <input class="field__input" :value="title" placeholder="请输入发票抬头" @input="title = $event.detail.value" />
            </view>

            <view v-if="titleType === 'COMPANY'" class="field">
              <text class="field__label">纳税人识别号 <text class="req">*</text></text>
              <input class="field__input" :value="taxNo" placeholder="统一社会信用代码" @input="taxNo = $event.detail.value" />
            </view>

            <view v-if="titleType === 'COMPANY'" class="field">
              <text class="field__label">开户银行</text>
              <input class="field__input" :value="bankName" placeholder="选填" @input="bankName = $event.detail.value" />
            </view>

            <view v-if="titleType === 'COMPANY'" class="field">
              <text class="field__label">银行账号</text>
              <input class="field__input" :value="bankAccount" placeholder="选填" @input="bankAccount = $event.detail.value" />
            </view>

            <view v-if="titleType === 'COMPANY'" class="field">
              <text class="field__label">企业地址</text>
              <input class="field__input" :value="companyAddress" placeholder="选填" @input="companyAddress = $event.detail.value" />
            </view>

            <view v-if="titleType === 'COMPANY'" class="field">
              <text class="field__label">企业电话</text>
              <input class="field__input" :value="companyPhone" placeholder="选填" @input="companyPhone = $event.detail.value" />
            </view>

            <view class="field">
              <text class="field__label">接收邮箱 <text class="req">*</text></text>
              <input class="field__input" :value="email" placeholder="用于接收电子发票" @input="email = $event.detail.value" />
            </view>

            <view class="actions">
              <view class="actions__primary" :class="{ 'is-disabled': submitting }" @tap="handleSubmit">
                <text>{{ submitting ? '提交中…' : '提交申请' }}</text>
              </view>
            </view>
          </view>
        </template>

        <view style="height: 40rpx;" />
      </view>
    </scroll-view>
  </view>
</template>

<script setup>
import { ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import * as orderApi from '@/api/order';
import * as userApi from '@/api/user';
import { getNavBarHeight } from '@/utils/system';
import { formatOrderAmount } from '@/utils/order';
import { requireLogin } from '@/utils/auth';

const navBarH = getNavBarHeight();

const orderNo = ref('');
const order = ref(null);
const existing = ref(null);
const loading = ref(true);
const submitting = ref(false);

const invoiceType = ref('NORMAL');
const titleType = ref('PERSONAL');
const title = ref('');
const taxNo = ref('');
const bankName = ref('');
const bankAccount = ref('');
const companyAddress = ref('');
const companyPhone = ref('');
const email = ref('');

const invoiceTypeOptions = [
  { value: 'NORMAL', label: '全电普通发票' },
  { value: 'SPECIAL', label: '全电专用发票' },
];

const INVOICE_STATUS_LABELS = { 0: '待开票', 1: '已开票', 2: '已驳回' };
const INVOICE_TYPE_LABELS = { NORMAL: '全电普通发票', SPECIAL: '全电专用发票' };

function invoiceStatusLabel(status) {
  return INVOICE_STATUS_LABELS[status] ?? '处理中';
}

function invoiceTypeLabel(type) {
  return INVOICE_TYPE_LABELS[type] ?? type;
}

function formatAmount(amount) {
  return formatOrderAmount(amount);
}

onLoad((opt) => {
  if (!requireLogin()) return;
  orderNo.value = opt?.orderNo || '';
  loadData();
});

async function loadData() {
  if (!orderNo.value) {
    loading.value = false;
    return;
  }
  loading.value = true;
  try {
    const [orderRes, invoiceRes, profileRes] = await Promise.all([
      orderApi.getOrderDetail(orderNo.value),
      orderApi.getInvoiceRequest(orderNo.value).catch(() => null),
      userApi.getMyProfile().catch(() => null),
    ]);
    order.value = orderRes;
    existing.value = invoiceRes || null;
    if (profileRes?.email) {
      email.value = profileRes.email;
    }
  } catch (_) {
    uni.showToast({ title: '加载失败', icon: 'none' });
  } finally {
    loading.value = false;
  }
}

function onInvoiceTypeChange(e) {
  invoiceType.value = e.detail.value;
}

function onTitleTypeChange(e) {
  titleType.value = e.detail.value;
}

async function handleSubmit() {
  if (submitting.value) return;
  if (!title.value.trim()) {
    uni.showToast({ title: '请填写发票抬头', icon: 'none' });
    return;
  }
  if (titleType.value === 'COMPANY' && !taxNo.value.trim()) {
    uni.showToast({ title: '企业抬头需填写纳税人识别号', icon: 'none' });
    return;
  }
  if (!email.value.trim()) {
    uni.showToast({ title: '请填写接收发票的邮箱', icon: 'none' });
    return;
  }

  submitting.value = true;
  try {
    const result = await orderApi.submitInvoiceRequest(orderNo.value, {
      invoiceType: invoiceType.value,
      titleType: titleType.value,
      title: title.value.trim(),
      taxNo: taxNo.value.trim(),
      bankName: bankName.value.trim(),
      bankAccount: bankAccount.value.trim(),
      companyAddress: companyAddress.value.trim(),
      companyPhone: companyPhone.value.trim(),
      email: email.value.trim(),
    });
    existing.value = result;
    uni.showToast({ title: '发票申请已提交', icon: 'success' });
  } catch (e) {
    uni.showToast({ title: e?.message || '提交失败', icon: 'none' });
  } finally {
    submitting.value = false;
  }
}
</script>

<style lang="scss" scoped>
.page {
  min-height: 100vh;
  background: $tk-bg-page;
}
.page__scroll {
  height: 100vh;
  box-sizing: border-box;
}
.page__inner {
  padding: $tk-sp-3;
  display: flex;
  flex-direction: column;
  gap: $tk-sp-3;
}

.tip {
  padding: $tk-sp-3;
  background: #FFFBEB;
  border: 2rpx solid #FDE68A;
  border-radius: $tk-radius-md;

  &__txt {
    font-size: $tk-fs-xs;
    color: #92400E;
    line-height: $tk-lh-normal;
  }
}

.status-card {
  background: $tk-bg-card;
  border-radius: $tk-radius-lg;
  padding: $tk-sp-4;
  box-shadow: $tk-shadow-card;

  &__title {
    font-size: $tk-fs-lg;
    font-weight: 700;
    color: #16A34A;
  }
  &__sub {
    display: block;
    margin-top: 8rpx;
    font-size: $tk-fs-sm;
    color: $tk-text-3;
  }
}

.readonly, .form {
  background: $tk-bg-card;
  border-radius: $tk-radius-lg;
  padding: $tk-sp-3;
  box-shadow: $tk-shadow-card;
}

.row {
  display: flex;
  justify-content: space-between;
  gap: $tk-sp-2;
  padding: 16rpx 0;
  border-bottom: 2rpx solid $tk-divider-light;

  &__k {
    font-size: $tk-fs-sm;
    color: $tk-text-4;
    flex-shrink: 0;
  }
  &__v {
    font-size: $tk-fs-sm;
    color: $tk-text-1;
    text-align: right;

    &--price {
      color: $tk-primary;
      font-weight: 700;
    }
  }
}

.field {
  display: flex;
  flex-direction: column;
  gap: 8rpx;
  margin-bottom: $tk-sp-3;

  &__label {
    font-size: $tk-fs-sm;
    color: $tk-text-2;
    font-weight: 600;
  }
  &__input {
    padding: 20rpx 24rpx;
    background: $tk-bg-page;
    border-radius: $tk-radius-md;
    font-size: $tk-fs-md;
  }
}

.req { color: $tk-primary; }

.radio-group {
  display: flex;
  flex-wrap: wrap;
  gap: $tk-sp-3;
}
.radio-row {
  display: flex;
  align-items: center;
  gap: 8rpx;
  font-size: $tk-fs-sm;
  color: $tk-text-2;
}

.actions__primary {
  padding: 24rpx;
  border-radius: $tk-radius-full;
  background: $tk-primary;
  text-align: center;
  color: #fff;
  font-weight: 700;

  &.is-disabled { opacity: 0.6; }
}
</style>
